server:
  port: 8088


---
server:
  connection-timeout: 5000

spring:
  profiles: default
  cloud:
    gateway:
      httpclient:
        pool.max-idle-time: 2000
      routes:
        - id: petmanagement
          uri: http://localhost:8081
          predicates:
            - Path=/pets/** 
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/items/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: petmanagement
          uri: http://petmanagement:8080
          predicates:
            - Path=/pets/** 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/items/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
