apiVersion: apps/v1
kind: Deployment
metadata:
  name: petmanagement
  labels:
    app: petmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petmanagement
  template:
    metadata:
      labels:
        app: petmanagement
    spec:
      containers:
        - name: petmanagement
          image: username/petmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5